# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y postgresql
     sudo echo "listen_addresses = '*'" >> /etc/postgresql/9.3/main/postgresql.conf
     sudo echo 'host    all             all             all                     md5' >> /etc/postgresql/9.3/main/pg_hba.conf
     sudo /etc/init.d/postgresql restart
     sudo -u postgres psql -c "create user vagrant with password 'vagrant444';"
     sudo -u postgres psql -c "ALTER USER vagrant WITH SUPERUSER;"
     # add vagrant user to access all databases from all addresses
     echo "localhost:5432:*:vagrant:vagrant444" > /home/vagrant/.pgpass
     sudo chown vagrant /home/vagrant/.pgpass
     sudo chmod 600 /home/vagrant/.pgpass
  SHELL
end
